"""20_build_statutes.py -- build, validate and write the Phase C statute table.

    python scripts/20_build_statutes.py --out data/statutes/statutes_v1.jsonl

The rows are generated by ``jurisuq.context.table.build_rows()`` -- a pure
function, so the JSONL has a stable sha256 on every machine and any later run
can prove it used the same table. Every row is validated (schema, date
boundaries, symmetric successor/predecessor links, offence clusters from
facts.OFFENCES) *before* anything is written: an invalid table is never left
on disk. A manifest with the file hash, row count and verified share is
written alongside the table.

PLATFORM NOTE (the reason for the explicit newline): files are written with
``newline="\\n"`` so the bytes -- and therefore the sha256 -- are identical on
Windows, Linux and macOS. Without it, Python's text-mode default translates
"\\n" to "\\r\\n" on Windows and the same table hashes differently there
(observed once on the target laptop: LF sha256 7be783e3... vs CRLF
4e1640e6...; identical rows, different line endings).

Human verification: every row ships ``verified: false``. When rows have been
checked against the official text (gazette + the Schedule to the Bharatiya
Nyaya Sanhita, 2023), record the result with ``scripts/22_verify_statutes.py``
(which writes ``data/statutes/statutes_v1.overrides.jsonl``) and re-run this
script: matching rows become ``verified: true`` and the manifest reports the
new verified share. The generated JSONL is never hand-edited.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from jurisuq.context.statute import validate_rows  # noqa: E402
from jurisuq.context.table import build_rows  # noqa: E402


def load_overrides(path: pathlib.Path) -> tuple[dict, list[str]]:
    """``key -> override dict`` from the overrides JSONL, if it exists."""
    if not path.exists():
        return {}, []
    out: dict[str, dict] = {}
    notes: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        key = " ".join(str(r.get("key", "")).upper().split())
        if not key:
            notes.append(f"override row without key skipped: {r}")
            continue
        out[key] = r
    return out, notes


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default="data/statutes/statutes_v1.jsonl",
                    help="where to write the JSONL table "
                         "(default: data/statutes/statutes_v1.jsonl)")
    ap.add_argument("--overrides",
                    default="data/statutes/statutes_v1.overrides.jsonl",
                    help="human-verification overrides JSONL (written by "
                         "22_verify_statutes.py --apply); applied when the "
                         "file exists")
    ap.add_argument("--no-overrides", action="store_true",
                    help="ignore the overrides file even if it exists")
    args = ap.parse_args()
    out = pathlib.Path(args.out)
    if not out.is_absolute():
        out = ROOT / out
    overrides_path = pathlib.Path(args.overrides)
    if not overrides_path.is_absolute():
        overrides_path = ROOT / overrides_path

    rows = build_rows()
    errors = validate_rows(rows)
    if errors:
        print("REFUSING TO WRITE: the generated table is invalid:")
        for e in errors:
            print(f"  - {e}")
        return 1

    # -- apply human-verification overrides (only ever flips `verified`) ------
    overrides: dict[str, dict] = {}
    unmatched: list[str] = []
    applied = 0
    if not args.no_overrides:
        overrides, notes = load_overrides(overrides_path)
        for n in notes:
            print(f"WARNING: {n}")
        if overrides:
            keys = {" ".join(f"{r['act']} {r['section']}".upper().split())
                    for r in rows}
            for key, ov in sorted(overrides.items()):
                if key not in keys:
                    unmatched.append(key)
                    continue
                if ov.get("verified") is True:
                    for r in rows:
                        if " ".join(f"{r['act']} {r['section']}".upper().split()) == key:
                            r["verified"] = True
                            applied += 1
            for key in unmatched:
                print(f"WARNING: override key not in table: {key!r} "
                      f"(recorded in manifest, row unchanged)")

    out.parent.mkdir(parents=True, exist_ok=True)
    existed_before = out.exists()
    payload = "".join(json.dumps(r, ensure_ascii=True) + "\n" for r in rows)
    # newline="\n": byte-identical output on every platform (see module note)
    out.write_text(payload, encoding="utf-8", newline="\n")
    sha = hashlib.sha256(out.read_bytes()).hexdigest()

    clusters = sorted({r["offence_cluster"] for r in rows})
    n_verified = sum(1 for r in rows if r["verified"])
    manifest = {
        "version": "statutes_v1",
        "created_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(
            timespec="seconds"),
        "n_rows": len(rows),
        "n_ipc": sum(1 for r in rows if r["act"] == "IPC"),
        "n_bns": sum(1 for r in rows if r["act"] == "BNS"),
        "offence_clusters": clusters,
        "n_clusters": len(clusters),
        "verified_rows": n_verified,
        "verified_share": n_verified / len(rows),
        "sha256": sha,
        "line_endings": "lf",
        "overwrote_existing": existed_before,
        "overrides_file": str(overrides_path) if overrides else None,
        "overrides_applied": applied,
        "overrides_unmatched": unmatched,
        "scope": ("the ten offence clusters of the frozen slice and the "
                  "provisions those clusters touch; not Indian criminal law"),
        "verification": ("every row verified=false until checked against the "
                         "official text (gazette + Schedule to the BNS, 2023); "
                         "record results with 22_verify_statutes.py --apply"),
    }
    manifest_path = out.with_name(out.stem + ".manifest.json")
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n",
                             encoding="utf-8", newline="\n")

    print(f"wrote {len(rows)} statute rows -> {out}")
    print(f"  IPC rows: {manifest['n_ipc']}   BNS rows: {manifest['n_bns']}")
    print(f"  offence clusters covered: {len(clusters)}/10")
    print(f"  verified rows: {n_verified}/{len(rows)} (share "
          f"{manifest['verified_share']:.2f})")
    if applied:
        print(f"  overrides applied: {applied} from {overrides_path}")
    print(f"  sha256: {sha}")
    print(f"  manifest: {manifest_path}")
    if n_verified == 0:
        print("  NOTE: verified share is 0.00 -- run the human verification "
              "pass (scripts/22_verify_statutes.py --export) before quoting "
              "any temporal factor from this table.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
